name: CI/CD Pipeline

on:
  push:
    branches:
      - "main"    # Trigger for dev deployment on push to main
    tags:
      - "v*"      # Trigger for prod deployment on tag creation (e.g., v1.0, v2.0)

jobs:
  build-and-deploy-dev:
    runs-on: ubuntu-latest
    environment: development  # Specify dev environment for dev deployment

    if: github.ref == 'refs/heads/main'  # Ensure this only runs on push to main

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install jq (JSON parser)
        run: |
          sudo apt-get update && sudo apt-get install -y jq

      - name: Authenticate with Render (Dev)
        env:
          RENDER_API_TOKEN: ${{ secrets.RENDER_API_TOKEN }}
        run: |
          if [ -z "$RENDER_API_TOKEN" ]; then
            echo "Render API token not provided."
            exit 1
          fi
          echo "Authenticated successfully with Render API."

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_IMAGE_NAME }}:latest .

      - name: Trigger Render Deployment (Dev)
        run: |
          response=$(curl -X POST https://api.render.com/deploy/${{ secrets.RENDER_DEPLOYMENT_HOOK_URL }})
          echo "Dev Deployment Triggered: $response"

      - name: Wait for Deployment to Finish (Dev)
        run: |
          deployment_status="pending"
          while [[ "$deployment_status" != "succeeded" && "$deployment_status" != "failed" ]]; do
            deployment_status=$(curl -s -X GET https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys/$deployment_id -H "Authorization: Bearer ${{ secrets.RENDER_API_TOKEN }}")
            deployment_status=$(echo "$deployment_status" | jq -r '.[0].deploy.status')
            echo "Current deployment status: $deployment_status"
            sleep 30
          done
          if [[ "$deployment_status" == "failed" ]]; then
            exit 1
          fi

  build-and-deploy-prod:
    runs-on: ubuntu-latest
    environment: production  # Specify prod environment for prod deployment

    if: startsWith(github.ref, 'refs/tags/v')  # Ensure this only runs on tag creation

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install jq (JSON parser)
        run: |
          sudo apt-get update && sudo apt-get install -y jq

      - name: Authenticate with Render (Prod)
        env:
          RENDER_API_TOKEN: ${{ secrets.RENDER_API_TOKEN }}
        run: |
          if [ -z "$RENDER_API_TOKEN" ]; then
            echo "Render API token not provided."
            exit 1
          fi
          echo "Authenticated successfully with Render API."

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_IMAGE_NAME }}:latest .

      - name: Trigger Render Deployment (Prod)
        run: |
          response=$(curl -X POST https://api.render.com/deploy/${{ secrets.RENDER_DEPLOYMENT_HOOK_URL }})
          echo "Prod Deployment Triggered: $response"

      - name: Wait for Deployment to Finish (Prod)
        run: |
          deployment_status="pending"
          while [[ "$deployment_status" != "succeeded" && "$deployment_status" != "failed" ]]; do
            deployment_status=$(curl -s -X GET https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys/$deployment_id -H "Authorization: Bearer ${{ secrets.RENDER_API_TOKEN }}")
            deployment_status=$(echo "$deployment_status" | jq -r '.[0].deploy.status')
            echo "Current deployment status: $deployment_status"
            sleep 30
          done
          if [[ "$deployment_status" == "failed" ]]; then
            exit 1
          fi
